spring:
  security:
    user:
      name: elvin
      password: 12345
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: update
    show-sql: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blogdb
    username: postgres
    password: 12345
server:
  port: 8081
